### ISSUE TITLE
Now: builds failing due to `COMMIT_SHA`

### ISSUE THREAD

**Issue by sohkai** [aragon/bonding.aragon.org#4]
We should update https://github.com/aragon/bonding.aragon.org/blob/master/next.config.js#L7 to handle the Now environment (see https://github.com/aragon/court-dashboard/blob/development/scripts/build.sh#L20-L21).

**Comment by bpierre** [comment]
Fixed by https://github.com/aragon/bonding.aragon.org/pull/3/commits/6c7f669dbbbb4c444e76c909c47dc08327f7b3e3
